Resolves issue 10.
cmsc436/sheets436 pull request #11
Opened 2017-04-15 20:25 UTC by krockpot

See code in doInBackground.

To test, delete the Fake Test sheet on our testing spreadsheet and change the app to write to that sheet (when it doesn't exist). The app will create the sheet and write to it (as usual).

I will remove the FAKE_TEST enum before merging.

2017-04-15 20:26 UTC, krockpot commented
This resolves #10

2017-04-15 20:35 UTC, MrPickles requested changes

2017-04-15 20:35 UTC, MrPickles commented on sheets436/src/main/java/edu/umd/cmsc436/sheets/Sheets.java
> +        FAKE("'Fake Test'"),
Don't have unless enums. Users are exposed to this. Run the actual enums on new spreadsheets.

2017-04-15 20:35 UTC, MrPickles commented on sheets436/src/main/java/edu/umd/cmsc436/sheets/WriteDataTask.java
> +                    } catch (Exception e2) {
It looks kinda like callback hell, except with try-catch. Is there any way you can refactor to make it cleaner (e.g. make the try blocks tighter)? When I was thinking about having a small, single layer try-catch around each call to `execute`.

2017-04-15 21:12 UTC, krockpot commented
Resolves #5

2017-04-15 21:14 UTC, krockpot commented on sheets436/src/main/java/edu/umd/cmsc436/sheets/Sheets.java
> +        FAKE("'Fake Test'"),
Removed / tested on completely blank spreadsheet.

2017-04-15 21:25 UTC, krockpot commented on sheets436/src/main/java/edu/umd/cmsc436/sheets/WriteDataTask.java
> +                    } catch (Exception e2) {
Separated into helper function.

2017-04-15 21:27 UTC, krockpot commented
Changes complete. Please re-review.

2017-04-16 01:46 UTC, MrPickles approved these changes

2017-04-16 01:46 UTC, MrPickles commented
LGTM

2017-04-16 03:02 UTC, merged